trigger:
  branches:
    include:
      - main

pool:
  name: Default  

stages:
  - stage: SetupApp
    displayName: 'Install NVIDIA GPU Driver and Launch Unreal Pixel Streaming App'
    jobs:
      - job: Deploy
        displayName: 'Install Driver, Configure Display, and Launch App'
        steps:

          # 1. Install NVIDIA Driver
          - task: PowerShell@2
            displayName: 'Download NVIDIA Driver'
            inputs:
              targetType: 'inline'
              script: |
                $url = "https://download.microsoft.com/download/1/1/d/11dd7071-c632-4a83-b950-d5eb3fdcf587/553.62_grid_win10_win11_server2019_server2022_dch_64bit_international_azure_swl.exe"
                $outPath = "C:\Temp\nvidia_driver.exe"
                Invoke-WebRequest -Uri $url -OutFile $outPath

          - task: PowerShell@2
            displayName: 'Install NVIDIA Driver Silently'
            inputs:
              targetType: 'inline'
              script: |
                Start-Process -FilePath "C:\Temp\nvidia_driver.exe" -ArgumentList "/s /noreboot" -Wait -NoNewWindow

          # 2. Set display resolution to 1920x1080 and only use 2 displays
          - task: PowerShell@2
            displayName: 'Set Display Resolution to 1920x1080 (Limit to 2 displays)'
            inputs:
              targetType: 'inline'
              script: |
                Add-Type -AssemblyName System.Windows.Forms
                $screens = [System.Windows.Forms.Screen]::AllScreens
                Write-Host "Found $($screens.Count) display(s)"

                if ($screens.Count -gt 2) {
                  Write-Host "Please manually disable extra monitors beyond 2."
                }

          - task: PowerShell@2
            displayName: 'Download ZIP Package'
            inputs:
              targetType: 'inline'
              script: |
                $url = "https://ue5filestorage.blob.core.windows.net/damac-utopia/Damac_Utopia_revised.zip?sp=r&st=2025-07-11T07:10:30Z&se=2025-08-01T15:10:30Z&spr=https&sv=2024-11-04&sr=b&sig=3wpnswblN71CqZzbQ0%2F0UWhPin2RTx8AXF7W9df0tsM%3D"
                $outputPath = "C:\Temp\app.zip"
                Invoke-WebRequest -Uri $url -OutFile $outputPath

          - task: PowerShell@2
            displayName: 'Extract ZIP Package'
            inputs:
              targetType: 'inline'
              script: |
                Expand-Archive -Path "C:\Temp\app.zip" -DestinationPath "C:\App" -Force

          - task: PowerShell@2
            displayName: 'Delete ZIP File'
            inputs:
              targetType: 'inline'
              script: |
                Remove-Item -Path "C:\Temp\app.zip" -Force

          - task: PowerShell@2
            displayName: 'Create Shortcut with Streaming Args'
            inputs:
              targetType: 'inline'
              script: |
                $exePath = Get-ChildItem -Path "C:\App\WindowsNoEditor" -Filter "*.exe" -Recurse | Select-Object -First 1
                $shortcutPath = "$env:USERPROFILE\Desktop\PixelStreaming.lnk"
                $WScriptShell = New-Object -ComObject WScript.Shell
                $shortcut = $WScriptShell.CreateShortcut($shortcutPath)
                $shortcut.TargetPath = $exePath.FullName
                $shortcut.Arguments = "-PixelStreamingIP=localhost -PixelStreamingPort=8888 -RenderOffscreen"
                $shortcut.WorkingDirectory = Split-Path $exePath.FullName
                $shortcut.Save()

          - task: PowerShell@2
            displayName: 'Run Web Server BAT File'
            inputs:
              targetType: 'inline'
              script: |
                $batPath = "C:\App\WindowsNoEditor\Damac_Hills_PS\Samples\PixelStreaming\WebServers\get_ps_servers.bat"
                Start-Process -FilePath $batPath -Wait

          - task: PowerShell@2
            displayName: 'Run setup.bat'
            inputs:
              targetType: 'inline'
              script: |
                $setupBat = "C:\App\WindowsNoEditor\Damac_Hills_PS\Samples\PixelStreaming\WebServers\SignallingWebServer\platform_scripts\cmd\setup.bat"
                Start-Process -FilePath $setupBat -Wait

          - task: PowerShell@2
            displayName: 'Run Start_With*.ps1'
            inputs:
              targetType: 'inline'
              script: |
                $ps1 = Get-ChildItem -Path "C:\App\WindowsNoEditor\Damac_Hills_PS\Samples\PixelStreaming\WebServers\SignallingWebServer\platform_scripts\cmd" -Filter "Start_With*.ps1" | Select-Object -First 1
                Start-Process -FilePath "powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -File `"$($ps1.FullName)`"" -NoNewWindow

          - task: PowerShell@2
            displayName: 'Launch App via Shortcut'
            inputs:
              targetType: 'inline'
              script: |
                $shortcut = "$env:USERPROFILE\Desktop\PixelStreaming.lnk"
                Start-Process -FilePath $shortcut
